#!/bin/bash
#
# Naive test for cmd-timer. Assumes default config.


# Don't allow sourcing.
if [ "$_" != "$0" ]; then
    echo "Please don't source this file."
    exit 1
fi

set -e
echo "Running tests..."
unset _CMDT_TIMER_PID
unset _CMDT_TIMER_COMMAND
unset _CMDT_TIMER_START


# Start the timer.
source cmd-timer start command param1 param2
# Test for the things that should be set on timer start.
if [ -z "$_CMDT_TIMER_PID" ]; then
    echo "_CMDT_TIMER_PID not set!"
    exit 1
fi
if [ "$_CMDT_TIMER_COMMAND" != "command" ]; then
    echo "_CMDT_TIMER_COMMAND not set correctly!"
    echo "Is: $_CMDT_TIMER_COMMAND"
    echo "Should be: command"
    exit 1
fi
if [ "$_CMDT_TIMER_PARAMS" != "param1 param2" ]; then
    echo "_CMDT_TIMER_PARAMS not set correctly!"
    echo "Is: $_CMDT_TIMER_PARAMS"
    echo "Should be: param1 param2"
    exit 1
fi


# Stop the timer.
source cmd-timer stop
# Test for the things that should be set on timer stop.
if [ -n "$_CMDT_TIMER_PID" ]; then
    echo "_CMDT_TIMER_PID is still set!"
    exit 1
fi
if [ -n "$_CMDT_TIMER_COMMAND" ]; then
    echo "_CMDT_TIMER_COMMAND is still set!"
    exit 1
fi
if [ -n "$_CMDT_TIMER_PARAMS" ]; then
    echo "_CMDT_TIMER_PARAMS is still set!"
    exit 1
fi
if [ -n "$_CMDT_TIMER_START" ]; then
    echo "_CMDT_TIMER_START is still set!"
    exit 1
fi


# Install the timer.
source cmd-timer install
if [ ! -f ~/.cmd-timer ]; then
    echo "Script not in place after installation!"
    exit 1
fi


# Uninstall the timer.
source cmd-timer uninstall <<< yy
if [ -f ~/.cmd-timer ]; then
    echo "Script still exists after uninstallation!"
    exit 1
fi


echo "Done."
